# Generated by Django 3.1.2 on 2021-02-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0005_delete_place_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('monday_time', models.TimeField()),
                ('tuesday_time', models.TimeField()),
                ('wednesday_time', models.TimeField()),
                ('thursday_time', models.TimeField()),
                ('friday_time', models.TimeField()),
                ('saturday_time', models.TimeField()),
                ('sunday_time', models.TimeField()),
            ],
        ),
    ]
