# Generated by Django 3.1.2 on 2021-02-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='unique_id',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
