# Generated by Django 3.1.2 on 2021-02-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20210224_0207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee',
        ),
    ]
