# Generated by Django 3.1.2 on 2021-03-01 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_lunchattendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lunchAttendance',
        ),
    ]
