# Generated by Django 3.1.2 on 2021-03-01 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_lunchattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunchattendance',
            name='timestamp',
        ),
    ]
